#!/bin/sh
# Convert .ss file to C string for easier embedding.

program="gen-c-string.sh"

if [ "x$1" = "x" ]; then
	cat <<EOF
Usage: $program [scheme-file1] [scheme-file2]...
Generage C string from scheme source files. Output is written to stdout.
EOF
	exit 1
fi

filestr="bundled_scripts"

echo "/* Generated with $program. Do not edit this file. */"
echo "static const char ${filestr}_content[] ="
cat $@ | sed -e '/^\s*$/d'    \
			 -e '/^[ \t]*;/d' \
			 -e 's/\\/\\\\/g' \
			 -e 's/"/\\"/g'   \
			 -e 's/\(.*\)/    " \1 "/' \
			 -e 's///g'
echo ';'
